XXLARGE_MAZE_C = \
    "########################\\"+\
    "#OOOO#OOOOOOOOOOOO#OOOO#\\"+\
    "#O##O#O#O###O####O#O##O#\\"+\
    "#OOOOOO#OO#OOOOO#OOOOOO#\\"+\
    "#O####O####OO####O####O#\\"+\
    "#OO#O#OOOOOOO#OOOO#OOOO#\\"+\
    "##O#O#O#O######O#O#O#O##\\"+\
    "#OO#O#O#OO#OOOOO#O###OO#\\"+\
    "#OOOO#O#O#####O##OOO#OO#\\"+\
    "#O##O###OO#OO#OO#OOO#OO#\\"+\
    "#OO#OOOOOOOOOOOO#O#O#OO#\\"+\
    "##O#O###O######O#O#O#O##\\"+\
    "#OO#O#OOOOOOOOOOOO#O#OO#\\"+\
    "#O####O####OO####O####O#\\"+\
    "#OO#OOO#OO#OOOOO#OOOOOO#\\"+\
    "#O##O#O#O######O###O##O#\\"+\
    "#OOOO#OOOOOOOOOOOO#OOGO#\\"+\
    "########################"