XXLARGE_MAZE = \
    "########################\\"+\
    "#OOOO#OOOOOOOOOOOO#OOOO#\\"+\
    "#O##O#O#O##OO##O#O#O##O#\\"+\
    "#OOOOOO#OOOOOOOO#OOOOOO#\\"+\
    "#O####O####OO####O####O#\\"+\
    "#OO#O#OOOOOOOOOOOO#O#OO#\\"+\
    "##O#O#O#O######O#O#O#O##\\"+\
    "#OO#OOO#OOOOOOOO#OOO#OO#\\"+\
    "#OOOOOO#OO#OO#OO#OOOOOO#\\"+\
    "#OOOOOO#OO#OO#OO#OOOOOO#\\"+\
    "#OO#OOO#OOOOOOOO#OOO#OO#\\"+\
    "##O#O#O#O######O#O#O#O##\\"+\
    "#OO#O#OOOOOOOOOOOO#O#OO#\\"+\
    "#O####O####OO####O####O#\\"+\
    "#OOOOOO#OOOOOOOO#OOOOOO#\\"+\
    "#O##O#O#O##OO##O#O#O##O#\\"+\
    "#OOOO#OOOOOOOOOOOO#OOGO#\\"+\
    "########################"